// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJJ8K8hhX9enadjliEkQ5F0PqqbzjPoUw',
    appId: '1:489277171730:web:a95015c713a04f8b6e50cb',
    messagingSenderId: '489277171730',
    projectId: 'bloodconnect-frontend',
    authDomain: 'bloodconnect-frontend.firebaseapp.com',
    storageBucket: 'bloodconnect-frontend.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGyEvIfPdJChgJ9VBP7_zI-ROon0dtpX0',
    appId: '1:489277171730:android:61b81d0a1196f7046e50cb',
    messagingSenderId: '489277171730',
    projectId: 'bloodconnect-frontend',
    storageBucket: 'bloodconnect-frontend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxVX5ij97iKxUFBj5pCbxbH6X_agi6BY0',
    appId: '1:489277171730:ios:2c5a22c309fbc4056e50cb',
    messagingSenderId: '489277171730',
    projectId: 'bloodconnect-frontend',
    storageBucket: 'bloodconnect-frontend.appspot.com',
    iosBundleId: 'com.example.bloodconnectFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxVX5ij97iKxUFBj5pCbxbH6X_agi6BY0',
    appId: '1:489277171730:ios:088ba76c635176676e50cb',
    messagingSenderId: '489277171730',
    projectId: 'bloodconnect-frontend',
    storageBucket: 'bloodconnect-frontend.appspot.com',
    iosBundleId: 'com.example.bloodconnectFrontend.RunnerTests',
  );
}
